# -*- coding: utf-8 -*-
"""Palm-Leaf Manuscript Restoration and Writing Segmentation Using Digital Image Processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F41ODHPQVYGKOxEVGwG55t-nNDB0TQ6z
"""

from google.colab import files

uploaded = files.upload()

import zipfile
import os

zip_file = "data_set.zip"

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall("/content")

print("Dataset extracted successfully!")

import os

print(os.listdir("/content"))

import os

dataset_path = "/content/data_set"

images = [
    f for f in os.listdir(dataset_path)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
]

print("Dataset path:", dataset_path)
print("Number of images:", len(images))
print("\nImage files:")

for i, image in enumerate(images, 1):
    print(i, "-", image)

import cv2
import matplotlib.pyplot as plt
import os

plt.figure(figsize=(15, 10))

for i, filename in enumerate(images[:6]):

    path = os.path.join(dataset_path, filename)

    img = cv2.imread(path)

    if img is None:
        print("Could not read:", filename)
        continue

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    plt.subplot(2, 3, i + 1)
    plt.imshow(img_rgb)
    plt.title(filename)
    plt.axis("off")

plt.tight_layout()
plt.show()

import cv2
import matplotlib.pyplot as plt
import os

# Select one image from your dataset
selected_file = images[0]

# Full image path
image_path = os.path.join(dataset_path, selected_file)

# Read image
image = cv2.imread(image_path)

# Convert BGR to RGB for displaying
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Convert to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Display original and grayscale
plt.figure(figsize=(16, 6))

plt.subplot(1, 2, 1)
plt.imshow(image_rgb)
plt.title("Original Palm-Leaf Manuscript")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(gray, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")

plt.tight_layout()
plt.show()

print("Selected image:", selected_file)
print("Original image shape:", image.shape)
print("Grayscale image shape:", gray.shape)

# Median filtering for noise removal

median = cv2.medianBlur(gray, 5)

# Display before and after filtering
plt.figure(figsize=(16, 6))

plt.subplot(1, 2, 1)
plt.imshow(gray, cmap="gray")
plt.title("Before Median Filtering")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(median, cmap="gray")
plt.title("After Median Filtering")
plt.axis("off")

plt.tight_layout()
plt.show()

# Illumination correction

# Estimate the background illumination
background = cv2.GaussianBlur(median, (0, 0), 21)

# Correct uneven illumination
corrected = cv2.divide(
    median,
    background,
    scale=255
)

# Display result
plt.figure(figsize=(16, 6))

plt.subplot(1, 2, 1)
plt.imshow(median, cmap="gray")
plt.title("After Median Filtering")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(corrected, cmap="gray")
plt.title("After Illumination Correction")
plt.axis("off")

plt.tight_layout()
plt.show()

# Contrast enhancement using CLAHE

clahe = cv2.createCLAHE(
    clipLimit=2.0,
    tileGridSize=(8, 8)
)

enhanced = clahe.apply(corrected.astype("uint8"))

# Display before and after enhancement
plt.figure(figsize=(16, 6))

plt.subplot(1, 2, 1)
plt.imshow(corrected, cmap="gray")
plt.title("Before CLAHE")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(enhanced, cmap="gray")
plt.title("After CLAHE")
plt.axis("off")

plt.tight_layout()
plt.show()

# Otsu thresholding for manuscript writing segmentation

otsu_threshold, otsu = cv2.threshold(
    enhanced,
    0,
    255,
    cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU
)

print("Otsu threshold value:", otsu_threshold)

# Display original and segmented image
plt.figure(figsize=(16, 6))

plt.subplot(1, 2, 1)
plt.imshow(enhanced, cmap="gray")
plt.title("Enhanced Manuscript")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(otsu, cmap="gray")
plt.title("Otsu Segmentation")
plt.axis("off")

plt.tight_layout()
plt.show()

# Adaptive thresholding

adaptive = cv2.adaptiveThreshold(
    enhanced,
    255,
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
    cv2.THRESH_BINARY_INV,
    31,
    8
)

# Compare Otsu and Adaptive Thresholding
plt.figure(figsize=(16, 6))

plt.subplot(1, 2, 1)
plt.imshow(otsu, cmap="gray")
plt.title("Otsu Thresholding")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(adaptive, cmap="gray")
plt.title("Adaptive Thresholding")
plt.axis("off")

plt.tight_layout()
plt.show()

# Morphological post-processing

kernel = cv2.getStructuringElement(
    cv2.MORPH_ELLIPSE,
    (3, 3)
)

cleaned = cv2.morphologyEx(
    adaptive,
    cv2.MORPH_OPEN,
    kernel
)

cleaned = cv2.morphologyEx(
    cleaned,
    cv2.MORPH_CLOSE,
    kernel
)

# Display before and after morphology
plt.figure(figsize=(16, 6))

plt.subplot(1, 2, 1)
plt.imshow(adaptive, cmap="gray")
plt.title("Before Morphological Processing")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(cleaned, cmap="gray")
plt.title("After Morphological Processing")
plt.axis("off")

plt.tight_layout()
plt.show()

# Connected component analysis

num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(
    cleaned,
    connectivity=8
)

print("Total connected components:", num_labels - 1)

# Copy grayscale image for drawing detected regions
result = cv2.cvtColor(gray, cv2.COLOR_GRAY2RGB)

# Draw bounding boxes around sufficiently large regions
for i in range(1, num_labels):

    x = stats[i, cv2.CC_STAT_LEFT]
    y = stats[i, cv2.CC_STAT_TOP]
    w = stats[i, cv2.CC_STAT_WIDTH]
    h = stats[i, cv2.CC_STAT_HEIGHT]
    area = stats[i, cv2.CC_STAT_AREA]

    # Ignore very small regions
    if area > 20:
        cv2.rectangle(
            result,
            (x, y),
            (x + w, y + h),
            (0, 255, 0),
            1
        )

# Display result
plt.figure(figsize=(15, 6))
plt.imshow(result)
plt.title("Detected Connected Writing Regions")
plt.axis("off")
plt.show()

# Create final segmentation mask

final_mask = (cleaned > 0).astype("uint8") * 255

# Create a color copy of the original image
overlay = image_rgb.copy()

# Highlight segmented writing regions
overlay[final_mask > 0] = [255, 0, 0]

# Display original, mask and overlay
plt.figure(figsize=(18, 6))

plt.subplot(1, 3, 1)
plt.imshow(image_rgb)
plt.title("Original Manuscript")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(final_mask, cmap="gray")
plt.title("Final Segmentation Mask")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(overlay)
plt.title("Segmentation Overlay")
plt.axis("off")

plt.tight_layout()
plt.show()

import os
import cv2

output_dir = "/content/results"
os.makedirs(output_dir, exist_ok=True)

cv2.imwrite(
    os.path.join(output_dir, "original.jpg"),
    cv2.cvtColor(image_rgb, cv2.COLOR_RGB2BGR)
)

cv2.imwrite(
    os.path.join(output_dir, "restored.jpg"),
    enhanced
)

cv2.imwrite(
    os.path.join(output_dir, "segmentation_mask.jpg"),
    final_mask
)

cv2.imwrite(
    os.path.join(output_dir, "segmentation_overlay.jpg"),
    cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR)
)

print("Results saved successfully!")
print("Location:", output_dir)